--DROP DATABASE
DROP DATABASE AVALIACAO;

--Criação do Banco de Dados
CREATE DATABASE AVALIACAO;

--Definir banco de dados
USE AVALIACAO;
GO

--TABELA CLIENTE
DROP TABLE CLIENTE;
GO

CREATE TABLE CLIENTE(
		ID INT IDENTITY(1, 1) NOT NULL,
		NOME VARCHAR(50),
		EMAIL VARCHAR(50),
		SENHA VARCHAR(128),
		USERNAME VARCHAR(64),
		DATA_NASCIMENTO DATE,
		COD_PLANO INT,
		CONSTRAINT PK_CLIENTE PRIMARY KEY(ID),
		CONSTRAINT FK_CLIENTE_PLANO FOREIGN KEY(COD_PLANO)
		REFERENCES DBO.PLANO(COD_PLANO)		
);
GO

--TABELA PLANO
DROP TABLE PLANO;
GO

CREATE TABLE PLANO(
		COD_PLANO INT IDENTITY(1, 1) NOT NULL,
		DESCRICAO VARCHAR(30),
		NUMERO_CARTAO CHAR(16),
		NOMES_USUARIOS VARCHAR(64),
		EMAIL_MEMBROS VARCHAR(200),
		CONSTRAINT PK_PLANO PRIMARY KEY(COD_PLANO)
);
GO

--TABELA USUARIO

DROP TABLE USUARIO;
GO

CREATE TABLE USUARIO(
		ID_USUARIO INT IDENTITY(1, 1) NOT NULL,
		ID_CLIENTE INT,
		NOMES_USUARIOS VARCHAR(64),
		PLAYLISTS INT,
		CONSTRAINT PK_USUARIO PRIMARY KEY(ID_USUARIO),
		CONSTRAINT FK_USUARIO_ID FOREIGN KEY(ID_CLIENTE)
		REFERENCES DBO.CLIENTE(ID)
);
GO

--TABELA CONTEÚDO

DROP TABLE CONTEUDO;
GO

CREATE TABLE CONTEUDO(
		ID_CONTEUDO INT IDENTITY NOT NULL,
		ID_PRODUTOR INT NOT NULL,
		NOME VARCHAR(50),
		TIPO INT NOT NULL,
		GENERO VARCHAR(50),
		ARTISTA VARCHAR(50),
		ALBUM VARCHAR(50),
		LETRA VARCHAR(50),
		TRANSCRICAO VARCHAR(MAX),
		CONSTRAINT PK_CONTEUDO PRIMARY KEY(ID_CONTEUDO),
		CONSTRAINT FK_CONTEUDO FOREIGN KEY(ID_PRODUTOR)
		REFERENCES DBO.PRODUTOR
);
GO

--TABELA PRODUTOR

DROP TABLE PRODUTOR;
GO

CREATE TABLE PRODUTOR(
		ID_PRODUTOR INT IDENTITY NOT NULL,
		NOME VARCHAR(30),
		EMAIL VARCHAR(50) NOT NULL,
		CPF VARCHAR(11),
		RG VARCHAR(7),
		CNPJ VARCHAR(14),
		IE VARCHAR(9),
		TIPO VARCHAR(20),
		CONSTRAINT PK_PRODUTOR PRIMARY KEY(ID_PRODUTOR)
);
GO